// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: client.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    client_id,
    client_secret,
    name,
    description,
    website,
    redirect_uri,
    is_public
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, client_id, client_secret, name, description, website, redirect_uri, is_public, created_at, updated_at
`

type CreateClientParams struct {
	ClientID     string         `json:"client_id"`
	ClientSecret string         `json:"client_secret"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Website      sql.NullString `json:"website"`
	RedirectUri  string         `json:"redirect_uri"`
	IsPublic     bool           `json:"is_public"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.ClientID,
		arg.ClientSecret,
		arg.Name,
		arg.Description,
		arg.Website,
		arg.RedirectUri,
		arg.IsPublic,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.RedirectUri,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClientByClientID = `-- name: GetClientByClientID :one
SELECT id, client_id, client_secret, name, description, website, redirect_uri, is_public, created_at, updated_at FROM clients
WHERE client_id = $1 LIMIT 1
`

func (q *Queries) GetClientByClientID(ctx context.Context, clientID string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByClientID, clientID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.RedirectUri,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, client_id, client_secret, name, description, website, redirect_uri, is_public, created_at, updated_at FROM clients
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClientByID(ctx context.Context, id int32) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.RedirectUri,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, client_id, client_secret, name, description, website, redirect_uri, is_public, created_at, updated_at FROM clients
ORDER BY created_at DESC
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecret,
			&i.Name,
			&i.Description,
			&i.Website,
			&i.RedirectUri,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET
    name = $2,
    description = $3,
    website = $4,
    redirect_uri = $5,
    is_public = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, client_id, client_secret, name, description, website, redirect_uri, is_public, created_at, updated_at
`

type UpdateClientParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Website     sql.NullString `json:"website"`
	RedirectUri string         `json:"redirect_uri"`
	IsPublic    bool           `json:"is_public"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Website,
		arg.RedirectUri,
		arg.IsPublic,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.RedirectUri,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientSecret = `-- name: UpdateClientSecret :one
UPDATE clients
SET
    client_secret = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, client_id, client_secret, name, description, website, redirect_uri, is_public, created_at, updated_at
`

type UpdateClientSecretParams struct {
	ID           int32  `json:"id"`
	ClientSecret string `json:"client_secret"`
}

func (q *Queries) UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClientSecret, arg.ID, arg.ClientSecret)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.RedirectUri,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
