// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Session struct {
	ID              int32          `json:"id"`
	RefreshToken    string         `json:"refresh_token"`
	TokenFamily     string         `json:"token_family"`
	DeviceName      sql.NullString `json:"device_name"`
	IpAddress       sql.NullString `json:"ip_address"`
	UserAgent       sql.NullString `json:"user_agent"`
	ExpiresAt       time.Time      `json:"expires_at"`
	Status          string         `json:"status"`
	FamilyVersion   int32          `json:"family_version"`
	CreatedAt       time.Time      `json:"created_at"`
	LastAccessedAt  time.Time      `json:"last_accessed_at"`
	PreviousTokenID sql.NullInt32  `json:"previous_token_id"`
	UserID          int32          `json:"user_id"`
}

type User struct {
	ID                  int32          `json:"id"`
	FirstName           string         `json:"first_name"`
	LastName            string         `json:"last_name"`
	Username            string         `json:"username"`
	Email               string         `json:"email"`
	EmailVerified       bool           `json:"email_verified"`
	PasswordHash        string         `json:"password_hash"`
	PhoneNumber         sql.NullString `json:"phone_number"`
	PhoneNumberVerified bool           `json:"phone_number_verified"`
	IsActive            bool           `json:"is_active"`
	MfaEnabled          bool           `json:"mfa_enabled"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}
