// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type User struct {
	ID                  int32          `json:"id"`
	FirstName           string         `json:"first_name"`
	LastName            string         `json:"last_name"`
	Username            string         `json:"username"`
	Email               string         `json:"email"`
	EmailVerified       bool           `json:"email_verified"`
	PasswordHash        string         `json:"password_hash"`
	PhoneNumber         sql.NullString `json:"phone_number"`
	PhoneNumberVerified bool           `json:"phone_number_verified"`
	IsActive            bool           `json:"is_active"`
	MfaEnabled          bool           `json:"mfa_enabled"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}
