// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (int32, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserByIdentifier(ctx context.Context, username string) (User, error)
	GetUserByPhoneNumber(ctx context.Context, phoneNumber sql.NullString) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
